<script setup>
import { computed, ref } from 'vue'; import { useRoute } from 'vue-router';
import { BarChart3, Building, Building2, ChevronDown, FileEdit, FileText, Hash, LayoutDashboard, LogOut, Package, PanelLeftClose, PanelLeftOpen, Receipt, TrendingDown, TrendingUp, UserCog, Users, Wallet, CreditCard, X } from 'lucide-vue-next';
import { useUiStore } from '@/stores/ui'; import DevspaceLogo from './DevspaceLogo.vue'; import SidebarNavItem from './SidebarNavItem.vue'; import SidebarSection from './SidebarSection.vue';
const ui = useUiStore(); const route = useRoute(); const showUserMenu = ref(false); const isCollapsed = computed(() => ui.sidebarCollapsed); const groups = [
 { label: 'Dashboard', items: [{ label: 'Dashboard', to: '/dashboard', icon: LayoutDashboard }] },
 { label: 'Master Data', items: [{ label: 'Klien', to: '/klien', icon: Users }, { label: 'Vendor', to: '/vendor', icon: Building2 }, { label: 'Produk & Layanan', to: '/produk-layanan', icon: Package }, { label: 'Rekening', to: '/rekening', icon: CreditCard }] },
 { label: 'Transaksi', items: [{ label: 'Invoice', to: '/invoice', icon: FileText }, { label: 'Billing', to: '/billing', icon: Receipt }, { label: 'Pembayaran', to: '/pembayaran', icon: Wallet }, { label: 'Pemasukan', to: '/pemasukan', icon: TrendingUp }, { label: 'Pengeluaran', to: '/pengeluaran', icon: TrendingDown }] },
 { label: 'Laporan', items: [{ label: 'Laporan', to: '/laporan', icon: BarChart3 }] },
 { label: 'Pengaturan', items: [{ label: 'Data Perusahaan', to: '/data-perusahaan', icon: Building }, { label: 'Template Invoice', to: '/template-invoice', icon: FileEdit }, { label: 'Penomoran Invoice', to: '/penomoran-invoice', icon: Hash }, { label: 'Pengguna & Hak Akses', to: '/pengguna', icon: UserCog }] },
]; const active = (item) => route.path === item.to; const closeMobile = () => ui.closeMobileSidebar();
</script>
<template><button v-if="ui.mobileSidebarOpen" aria-label="Tutup navigasi" class="fixed inset-0 z-30 bg-black/35 lg:hidden" @click="closeMobile" /><aside :class="['fixed inset-y-0 left-0 z-40 flex h-full flex-col border-r border-[#E2E6EC] bg-white transition-[width,transform] duration-200 lg:static lg:z-auto lg:translate-x-0 lg:shrink-0', isCollapsed ? 'w-[76px]' : 'w-[236px]', ui.mobileSidebarOpen ? 'translate-x-0' : '-translate-x-full']"><div :class="['flex h-[52px] shrink-0 items-center border-b border-[#E2E6EC]', isCollapsed ? 'justify-center px-2' : 'gap-2.5 px-5']"><DevspaceLogo :size="26" /><div v-if="!isCollapsed" class="min-w-0 flex-1"><div class="text-[13px] font-bold leading-none tracking-tight text-[#172033]">DEVSPACE</div><div class="mt-0.5 text-[10px] font-medium leading-none tracking-wide text-[#9CA3AF]">Invoicing &amp; Billing</div></div><button class="hidden rounded p-1 text-[#A0AABB] hover:bg-[#F5F7FA] hover:text-[#667085] lg:inline-flex" :aria-label="isCollapsed ? 'Perluas sidebar' : 'Ciutkan sidebar'" @click="ui.toggleSidebar"><component :is="isCollapsed ? PanelLeftOpen : PanelLeftClose" :size="16" /></button><button class="rounded p-1 text-[#A0AABB] hover:bg-[#F5F7FA] lg:hidden" aria-label="Tutup navigasi" @click="closeMobile"><X :size="16" /></button></div><nav class="sidebar-nav flex-1 overflow-y-auto px-3 py-2.5" :class="isCollapsed && 'px-2'"><SidebarSection v-for="group in groups" :key="group.label" :label="group.label" :collapsed="isCollapsed"><SidebarNavItem v-for="item in group.items" :key="item.to" :item="item" :active="active(item)" :collapsed="isCollapsed" @navigate="closeMobile" /></SidebarSection></nav><div class="relative border-t border-[#E2E6EC] py-2.5" :class="isCollapsed ? 'px-2' : 'px-3'"><button :title="isCollapsed ? 'Fazri Lukman — Admin / Finance' : undefined" :class="['flex w-full items-center rounded-md py-2 transition-colors hover:bg-[#F5F7FA]', isCollapsed ? 'justify-center px-0' : 'gap-2.5 px-2']" @click="showUserMenu = !showUserMenu"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#173B6C] text-[11px] font-semibold text-white">FL</span><span v-if="!isCollapsed" class="min-w-0 flex-1 text-left"><span class="block truncate text-[13px] font-medium leading-snug text-[#172033]">Fazri Lukman</span><span class="block text-[10px] leading-snug text-[#9CA3AF]">Admin / Finance</span></span><ChevronDown v-if="!isCollapsed" :size="13" class="shrink-0 text-[#B0BAC7]" /></button><div v-if="showUserMenu" :class="['absolute bottom-full mb-1 rounded-lg border border-[#E2E6EC] bg-white py-1 shadow-lg', isCollapsed ? 'left-2 w-48' : 'left-3 right-3']"><button class="flex w-full items-center gap-2.5 px-3 py-2 text-sm text-red-600 hover:bg-red-50"><LogOut :size="14" />Keluar</button></div></div></aside></template>
