<script setup>
import { computed } from 'vue';
import { formatInvoiceCurrency, formatInvoiceDate } from '@/utils/formatters';
import invoiceBackground from '../../../images/invoice/bg-invoice.png';

const props = defineProps({ invoice: { type: Object, required: true }, company: { type: Object, required: true }, client: Object, paymentAccount: Object, template: { type: Object, required: true } });
const subtotal = computed(() => props.invoice.items?.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.qty || 0), 0) || 0);
const total = computed(() => subtotal.value - Number(props.invoice.discount || 0));
</script>

<template>
  <article class="invoice-document invoice-print relative min-h-[297mm] w-[210mm] shrink-0 overflow-hidden bg-white px-[20mm] py-[13mm] text-[14.72px] leading-[1.2] text-[#171717]">
    <img class="invoice-background absolute inset-0" :src="invoiceBackground" alt="" aria-hidden="true" /><img class="invoice-background invoice-background--bottom absolute inset-0" :src="invoiceBackground" alt="" aria-hidden="true" />
    <svg class="accent top-0 right-0" viewBox="0 0 12 74" aria-hidden="true"><rect width="12" height="74" fill="#626ca8" /></svg><svg class="accent accent-mid top-[74px] right-0" viewBox="0 0 12 63" aria-hidden="true"><rect width="12" height="63" fill="#d9e1f3" /></svg><svg class="accent accent-light top-[137px] right-0" viewBox="0 0 12 62" aria-hidden="true"><rect width="12" height="62" fill="#ebeff8" /></svg><svg class="accent bottom-0 left-0" viewBox="0 0 12 74" aria-hidden="true"><rect width="12" height="74" fill="#626ca8" /></svg><svg class="accent accent-mid bottom-[74px] left-0" viewBox="0 0 12 63" aria-hidden="true"><rect width="12" height="63" fill="#d9e1f3" /></svg><svg class="accent accent-light bottom-[137px] left-0" viewBox="0 0 12 62" aria-hidden="true"><rect width="12" height="62" fill="#ebeff8" /></svg>
    <div class="relative z-10 flex min-h-[265mm] flex-col">
      <header class="invoice-header grid items-center"><img v-if="template.showLogo" :src="company.logoUrl" :alt="company.name" class="h-[46px] max-w-[235px] object-contain object-left" /><div v-if="template.showTagline" class="invoice-tagline text-center"><p class="invoice-tagline__title">{{ company.tagline }}</p><p class="invoice-tagline__contact text-[#777]">Website: {{ company.website }} | Email: {{ company.email }}</p></div></header>
      <section class="mt-[56px] grid grid-cols-[1fr_auto] gap-8"><div class="space-y-1.5 leading-tight"><p><b class="inline-block w-[123px]">Invoice Name</b>: {{ invoice.name }}</p><p v-if="template.showInvoiceDate"><b class="inline-block w-[123px]">Invoice Date</b>: {{ formatInvoiceDate(invoice.date) }}</p><p v-if="template.showDueDate"><b class="inline-block w-[123px]">Due Date</b>: {{ formatInvoiceDate(invoice.dueDate) }}</p></div><div class="min-w-[210px] text-right"><h1 v-if="template.showTitle" class="text-[13.44px] font-bold">{{ template.title }}</h1><p v-if="template.showNumber" class="mt-1">No. {{ invoice.number }}</p></div></section>
      <section class="mt-10 grid grid-cols-2 gap-8"><div v-if="template.showClient"><b>Bill To:</b><p class="mt-1 leading-[1.2]">{{ invoice.client }}<br>{{ client?.alamat || '-' }}<br><span v-if="client?.telepon">{{ client.telepon }}</span><span v-else>{{ client?.email }}</span></p></div><div class="pl-2"><b>Total Due:</b><p class="mt-1 text-[14.72px]">{{ formatInvoiceCurrency(total) }}</p></div></section>
      <table v-if="template.showItems" class="mt-12 w-full border-collapse leading-tight"><thead class="bg-[#f4f4f4]"><tr class="border border-[#7b7b7b]"><th class="border-r border-[#7b7b7b] px-2 py-1.5 text-center">Item Description</th><th class="w-[19%] border-r border-[#7b7b7b] px-2 py-1.5 text-center">Price</th><th class="w-[12%] border-r border-[#7b7b7b] px-2 py-1.5 text-center">Qty</th><th class="w-[21%] px-2 py-1.5 text-center">Total</th></tr></thead><tbody><tr v-for="item in invoice.items" :key="item.id" class="border border-t-0 border-[#7b7b7b]"><td class="border-r border-[#7b7b7b] px-2 py-1.5">{{ item.description || item.product }}</td><td class="border-r border-[#7b7b7b] px-2 py-1.5 text-right">{{ formatInvoiceCurrency(item.price) }}</td><td class="border-r border-[#7b7b7b] px-2 py-1.5 text-center">{{ item.qty }}</td><td class="px-2 py-1.5 text-right">{{ formatInvoiceCurrency(item.price * item.qty) }}</td></tr></tbody></table>
      <section class="ml-auto mt-2 w-[52%] leading-tight"><div v-if="template.showSubtotal" class="flex justify-between py-1.5"><b>Subtotal</b><span>{{ formatInvoiceCurrency(subtotal) }}</span></div><div v-if="template.showDiscount" class="flex justify-between py-1.5"><b>Discount</b><span>{{ invoice.discount ? formatInvoiceCurrency(invoice.discount) : '0' }}</span></div><div v-if="template.showTotal" class="flex justify-between border-t border-[#565656] py-2 text-[14.72px]"><b>Total Due</b><b>{{ formatInvoiceCurrency(total) }}</b></div></section>
      <section class="mt-11 max-w-[74%] leading-[1.35]"><div v-if="template.showBankInfo"><b>Payment Method:</b><p class="mt-2 font-semibold">{{ paymentAccount?.nama || '-' }} {{ paymentAccount?.nomor || '' }}</p><p>{{ paymentAccount?.atasNama || company.name }}</p><p v-if="paymentAccount?.cabang">{{ paymentAccount.cabang }}</p></div><div v-if="template.showTerms" class="mt-5"><b>Terms &amp; Condition:</b><ul class="mt-2 list-disc space-y-1 pl-5"><li>{{ invoice.terms || 'Silakan lakukan pembayaran ke rekening yang tertera di atas.' }}</li><li>Mohon konfirmasi pembayaran melalui email balasan pada email tagihan ini.</li></ul></div></section>
      <section v-if="template.showStamp || template.showSignature" class="mt-auto flex justify-end pt-12"><div class="w-[240px] text-center"><p>{{ company.signingCity || 'Bandung' }}, {{ formatInvoiceDate(invoice.date) }}</p><div class="relative mx-auto mt-2 flex h-[60px] w-[225px] items-center justify-center overflow-visible"><img v-if="template.showStamp" :src="company.stampUrl || company.logoUrl" class="absolute h-full w-full object-contain grayscale contrast-125" /><img v-if="template.showSignature && company.signatureUrl" :src="company.signatureUrl" class="relative z-10 h-[58px] max-w-[218px] translate-y-[14px] scale-[1.65] object-contain" /></div><p v-if="template.showSignerName" class="mt-6 font-bold">{{ company.signerName }}</p><p v-if="template.showSignerPosition">{{ company.signerPosition }}</p><p>{{ company.name }}</p></div></section>
      <footer class="mt-12 flex justify-between text-[13.44px]"><span>INVOICE<br>No. {{ invoice.number }}</span><span>1</span></footer>
    </div>
  </article>
</template>

<style scoped>
.invoice-document { width: 210mm; min-height: 297mm; flex-shrink: 0; font-family: 'Tamil Sangam MN', Arial, sans-serif; font-synthesis: weight; }
.invoice-document .invoice-header { grid-template-columns: 40% 60%; gap: 0; }.invoice-document .invoice-tagline { text-align: right; }.invoice-document .invoice-tagline__title { color: #172033; font-family: 'PT Sans', Arial, sans-serif; font-size: 16px; font-weight: 700; line-height: 1.2; white-space: nowrap; }.invoice-document .invoice-tagline__contact { margin-top: 2px; font-family: 'PT Sans', Arial, sans-serif; font-size: 10.56px; white-space: nowrap; }
.invoice-background { z-index: 0; width: 100%; height: 100%; object-fit: fill; pointer-events: none; }.invoice-background--bottom { transform: rotate(180deg); }.accent { position: absolute; z-index: 1; width: 12px; height: 74px; }.accent-mid { height: 63px; }.accent-light { height: 62px; }
@media print { @page { size: A4 portrait; margin: 0; }.invoice-print { height: 297mm !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
