<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { usePaymentStore } from '@/stores/payment';
import { useMasterDataStore } from '@/stores/masterData';
import { formatCurrency, todayIso } from '@/utils/formatters';
import BaseButton from '@/components/ui/BaseButton.vue'; import BaseInput from '@/components/ui/BaseInput.vue'; import BaseModal from '@/components/ui/BaseModal.vue'; import BaseSelect from '@/components/ui/BaseSelect.vue'; import BaseTextarea from '@/components/ui/BaseTextarea.vue';
const props=defineProps({open:Boolean,invoice:Object}); const emit=defineEmits(['close','saved']); const store=usePaymentStore(); const masterData=useMasterDataStore(); const accounts=computed(()=>masterData.activeRecordsFor('account')); const summary=computed(()=>store.paymentSummaryByInvoice(props.invoice)); const form=reactive({paymentDate:todayIso(),amount:'',method:'Transfer Bank',accountId:'',referenceNumber:'',proofName:'',proofFile:null,notes:''}); const error=ref(''),saving=ref(false);
const reset=()=>{form.paymentDate=todayIso();form.amount='';form.method='Transfer Bank';form.accountId=props.invoice?.accountId||accounts.value[0]?.id||'';form.referenceNumber='';form.proofName='';form.proofFile=null;form.notes='';error.value=''};watch(()=>props.open,(open)=>{if(open)reset()}); const fileChanged=(event)=>{const file=event.target.files?.[0];form.proofName=file?.name||'';form.proofFile=file||null};
const save=async()=>{if(saving.value)return;try{saving.value=true;await store.addPayment({invoiceId:props.invoice.id,paymentDate:form.paymentDate,amount:form.amount,method:form.method,accountId:form.accountId,referenceNumber:form.referenceNumber,proofFile:form.proofFile,notes:form.notes},props.invoice);emit('saved');emit('close')}catch(exception){error.value=exception.message}finally{saving.value=false}};
</script>
<template><BaseModal :open="open" title="Catat Pembayaran" size="md" @close="emit('close')"><div v-if="invoice" class="space-y-4"><div class="rounded-md bg-[#F9FAFB] p-3 text-sm"><div class="flex justify-between gap-4"><span class="text-[#667085]">Invoice</span><span class="font-medium text-[#172033]">{{invoice.number}}</span></div><div class="mt-1 flex justify-between gap-4"><span class="text-[#667085]">Klien</span><span class="text-right text-[#172033]">{{invoice.client}}</span></div><div class="mt-1 flex justify-between gap-4"><span class="text-[#667085]">Sisa Tagihan</span><span class="font-bold text-[#D97706]">{{formatCurrency(summary.remaining)}}</span></div></div><div class="grid gap-4 sm:grid-cols-2"><BaseInput v-model="form.paymentDate" label="Tanggal Pembayaran" type="date" required/><BaseInput v-model="form.amount" label="Nominal (Rp)" type="number" placeholder="0" required/></div><p v-if="error" class="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-600">{{error}}</p><BaseSelect v-model="form.method" label="Metode Pembayaran" :options="['Transfer Bank','Kas','Cek','QRIS']"/><BaseSelect v-model="form.accountId" label="Rekening Tujuan" :options="accounts.map(x=>({value:x.id,label:`${x.nama} — ${x.nomor}`}))"/><BaseInput v-model="form.referenceNumber" label="Nomor Referensi" placeholder="Nomor transfer / referensi bukti"/><div><label class="mb-1.5 block text-sm font-medium text-[#172033]">Bukti Pembayaran</label><input id="payment-proof" type="file" accept=".jpg,.jpeg,.png,.pdf" class="sr-only" @change="fileChanged"/><label for="payment-proof" class="block cursor-pointer rounded-md border-2 border-dashed border-[#E2E6EC] p-3 text-center text-xs text-[#9CA3AF] hover:bg-gray-50">{{form.proofName||'Klik untuk unggah bukti pembayaran (JPG, PDF, PNG)'}}</label></div><BaseTextarea v-model="form.notes" label="Catatan" placeholder="Catatan tambahan (opsional)" :rows="3"/></div><template #footer><BaseButton variant="secondary" @click="emit('close')">Batal</BaseButton><BaseButton :disabled="summary.remaining<=0" :loading="saving" @click="save">Simpan Pembayaran</BaseButton></template></BaseModal></template>
